//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cocodrilo_frame
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ล_กค_า
    {
        public int CustID { get; set; }
        public string CustFirstName { get; set; }
        public string CustLastName { get; set; }
        public Nullable<System.DateTime> CustBDay { get; set; }
        public string CustPhone { get; set; }
        public string CustEmail { get; set; }
    }
}
