//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cocodrilo_frame
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_จระเข_
    {
        public int CroID { get; set; }
        public string CroCategory { get; set; }
        public string CroBirth { get; set; }
        public Nullable<int> CroPrice { get; set; }
        public Nullable<int> CroNum { get; set; }
        public Nullable<int> FoodID { get; set; }
    }
}
