//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cocodrilo_frame
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_การซ__ออาหารจระเข_
    {
        public int FoodID { get; set; }
        public Nullable<System.DateTime> FoodDate { get; set; }
        public string FoodOfood { get; set; }
        public Nullable<int> FoodNumber { get; set; }
        public Nullable<int> FoodPrice { get; set; }
    }
}
