//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cocodrilo_frame
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ใบเสร_จ
    {
        public int BillID { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public Nullable<int> PayID { get; set; }
        public Nullable<int> CustID { get; set; }
        public string CustFristName { get; set; }
        public string CustLastName { get; set; }
        public Nullable<int> CroID { get; set; }
        public string CroCategory { get; set; }
        public string CroPrice { get; set; }
        public string CroNum { get; set; }
        public string OrderPrice { get; set; }
    }
}
